export const config = {
  port: parseInt(process.env.PORT || '3001', 10),
  clientUrl: process.env.CLIENT_URL || 'http://localhost:5173',
  pythonServiceUrl: process.env.PYTHON_SERVICE_URL || 'http://localhost:8000',
  internalSecret: process.env.INTERNAL_SERVICE_SECRET || 'dev-secret-change-me',
  anthropicApiKey: process.env.ANTHROPIC_API_KEY,
  anthropicModel: process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-20250514',
  llmProvider: (process.env.LLM_PROVIDER || 'groq').toLowerCase(),
  groqApiKey: process.env.GROQ_API_KEY,
  groqModel: process.env.GROQ_MODEL || 'llama-3.3-70b-versatile',
  groqBaseUrl: process.env.GROQ_BASE_URL || 'https://api.groq.com/openai/v1',
  maxFileSizeMb: parseInt(process.env.MAX_FILE_SIZE_MB || '25', 10),
  allowedFileTypes: (process.env.ALLOWED_FILE_TYPES || 'pdf,docx,txt,md,xlsx').split(','),
  topKChunks: parseInt(process.env.TOP_K_CHUNKS || '8', 10),
  similarityThreshold: parseFloat(process.env.SIMILARITY_THRESHOLD || '0.32'),
  analysisConcurrency: parseInt(process.env.ANALYSIS_CONCURRENCY || '3', 10),
  embedBatchSize: parseInt(process.env.EMBED_BATCH_SIZE || '64', 10),
  storageBucket: process.env.SUPABASE_STORAGE_BUCKET || 'documents',
};
